# Update Frontend Environment Variables Script
# This script retrieves CDK stack outputs and updates the frontend .env file

Write-Host "Retrieving CDK Stack Outputs..." -ForegroundColor Cyan

# Get stack outputs
$userPoolId = aws cloudformation describe-stacks --stack-name RetailMindApiStack --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text
$userPoolClientId = aws cloudformation describe-stacks --stack-name RetailMindApiStack --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" --output text
$apiEndpoint = aws cloudformation describe-stacks --stack-name RetailMindApiStack --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text

if (-not $userPoolId -or -not $userPoolClientId -or -not $apiEndpoint) {
    Write-Host "Error: Could not retrieve all stack outputs. Make sure RetailMindApiStack is deployed." -ForegroundColor Red
    Write-Host "Run: cdk deploy RetailMindApiStack" -ForegroundColor Yellow
    exit 1
}

Write-Host "`nRetrieved values:" -ForegroundColor Green
Write-Host "  User Pool ID: $userPoolId"
Write-Host "  User Pool Client ID: $userPoolClientId"
Write-Host "  API Endpoint: $apiEndpoint"

# Update frontend .env file
$envPath = "frontend\.env"
$envContent = @"
# AWS Amplify Configuration
# Auto-generated by update-frontend-env.ps1
# Last updated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# AWS Region
VITE_AWS_REGION=us-east-1

# Cognito User Pool ID
VITE_USER_POOL_ID=$userPoolId

# Cognito User Pool Client ID
VITE_USER_POOL_CLIENT_ID=$userPoolClientId

# API Gateway URL
VITE_API_GATEWAY_URL=$apiEndpoint
"@

Set-Content -Path $envPath -Value $envContent

Write-Host "`nSuccessfully updated $envPath" -ForegroundColor Green
Write-Host "`nYou can now run the frontend:" -ForegroundColor Cyan
Write-Host "  cd frontend" -ForegroundColor Yellow
Write-Host "  npm run dev" -ForegroundColor Yellow
