#!/bin/bash
# Update Frontend Environment Variables Script
# This script retrieves CDK stack outputs and updates the frontend .env file

echo "Retrieving CDK Stack Outputs..."

# Get stack outputs
USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name RetailMindApiStack --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)
USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name RetailMindApiStack --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" --output text)
API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name RetailMindApiStack --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text)

if [ -z "$USER_POOL_ID" ] || [ -z "$USER_POOL_CLIENT_ID" ] || [ -z "$API_ENDPOINT" ]; then
    echo "Error: Could not retrieve all stack outputs. Make sure RetailMindApiStack is deployed."
    echo "Run: cdk deploy RetailMindApiStack"
    exit 1
fi

echo ""
echo "Retrieved values:"
echo "  User Pool ID: $USER_POOL_ID"
echo "  User Pool Client ID: $USER_POOL_CLIENT_ID"
echo "  API Endpoint: $API_ENDPOINT"

# Update frontend .env file
ENV_PATH="frontend/.env"
cat > "$ENV_PATH" << EOF
# AWS Amplify Configuration
# Auto-generated by update-frontend-env.sh
# Last updated: $(date '+%Y-%m-%d %H:%M:%S')

# AWS Region
VITE_AWS_REGION=us-east-1

# Cognito User Pool ID
VITE_USER_POOL_ID=$USER_POOL_ID

# Cognito User Pool Client ID
VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID

# API Gateway URL
VITE_API_GATEWAY_URL=$API_ENDPOINT
EOF

echo ""
echo "Successfully updated $ENV_PATH"
echo ""
echo "You can now run the frontend:"
echo "  cd frontend"
echo "  npm run dev"
